services:
  db:
    ports:
      - 5432:5432
    container_name: postgres_compose
    image: postgres
    environment:
      - POSTGRES_DB=gestaobanco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: .
    container_name: gestaobanc_compose
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/gestaobanco
      db-username: postgres
      db-password: postgres
    depends_on:
      - db